#
# $Id: makefile,v 1.2 2012/01/16 16:00:21 nikolov Exp $
#

ROOT  = ../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	ONNDataFormatsHelper.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

