#
# $Id: makefile,v 1.2 2011/10/05 15:03:46 nikolov Exp $
#

ROOT  = ../../../../..


GSON = $(ROOT)/../lib/gson.jar
AUXCLASSPATH = $(GSON)

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
    AllToAll.java \
    AllToOne.java \
    Connection.java \
    ConnectionType.java \
    Custom.java \
	OneToAll.java \
    OneToOne.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

