// File automatically generated by ESPAM

#ifndef input_H
#define input_H
#include "csdfNode.h"
#include <map>

class input : public csdfNode{
public:
    input();
    virtual ~input();

    void main(void *threadarg) override;
    // specific const parameters definition
    std::map<std::string,int> int_params;
  const int neurons = 1;

  //FIFO sizes
    int OP0_fifo_size;

  //data array definition
    const int data_dim_0 = 32;
    const int data_dim_1 = 32;
    int data[32][32] = {{0}};

  const int output_dims = 2;
  //output array definition
    const int output_dim_0 = 1;
    const int output_dim_1 = 32;
    int output[1][32] = {{0}};

  //specific node parameters and functions
};
#endif // input_H
