
ROOT  = ../../..

SUBPACKAGES = \
	polylibBIT

# Java files in this directory
JSRCS = \
	Enumeration.java \
	Lattice.java \
	LatticeUnion.java \
	ParamPolyhedron.java \
	Polyhedron.java \
	PolylibException.java \
	PolylibInterface.java \
	PolyLib.java \
	EValue.java \
	ParamDomain.java \
	ParamVertices.java \
	ENode.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

