#
# $Id: makefile,v 1.1 2007/12/07 22:09:11 stefanov Exp $
#

ROOT  = ../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	MProcess.java \
	MProcessor.java \
	MFifo.java \
	Mapping.java

	
# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

