#
# $Id: makefile,v 1.1 2007/12/07 22:07:24 stefanov Exp $
#

ROOT  = ../../..

SUBPACKAGES = \
	platform

# Java files in this directory
JSRCS = \

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

