#
#
#

ROOT  = ../../../../..

SUBPACKAGES = \


# Java files in this directory
JSRCS = \
    Operator.java  \
    ComplexOperator.java \
    InternalBuffer.java


# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

