#
# $Id: makefile,v 1.4 2012/05/02 16:25:45 tzhai Exp $
#

ROOT  = ../../../..

SUBPACKAGES = 

# Java files in this directory
JSRCS = \
	Options.java          \
    XpsNetworkVisitor.java \
	XpsProcessVisitor.java \
	XpsStaticProcessVisitor.java \
	XpsDynamicXilkernelProcessVisitor.java \
	XpsDynamicFreeRTOSProcessVisitor.java \
	XpsStatementVisitor.java \
	XmpVisitor.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

