#
# $Id: makefile,v 1.3 2012/04/19 17:52:58 mohamed Exp $
#

ROOT  = ../../../..

SUBPACKAGES = 

# Java files in this directory
JSRCS = \
	XpsNetworkVisitor.java \
	XpsProcessVisitor.java \
	XpsStaticProcessVisitor.java \
	XpsDynamicXilkernelProcessVisitor.java \
	XpsDynamicFreeRTOSProcessVisitor.java \
	XpsStatementVisitor.java \
	XmpVisitor.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

