#
# $Id: makefile,v 1.1 2007/12/07 22:09:07 stefanov Exp $
#

ROOT  = ../../..

SUBPACKAGES = \
	cdpn


# Java files in this directory
JSRCS = \
	Gate.java \
	Channel.java \
	Process.java \
	ProcessNetwork.java


# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

