

ROOT  = ../../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	CeilTerm.java \
	DivTerm.java \
	Expression.java \
	FloorTerm.java \
	MaximumTerm.java \
	MinimumTerm.java \
	ModTerm.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

