#
#
#

ROOT  = ../../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
    HDNNVisitorTensorrt.java \
    HDNNVisitorARMCL.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

