#
# $Id: makefile,v 1.1 2007/12/07 22:09:10 stefanov Exp $
#

ROOT  = ../../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	ADGVariable.java \
	ADGParameter.java \
	ADGFunction.java \
	ADGPort.java \
	ADGInPort.java \
	ADGOutPort.java \
	ADGEdge.java \
	ADGNode.java \
	ADGraph.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

