#
# $Id: makefile,v 1.2 2011/10/05 15:03:46 nikolov Exp $
#

ROOT  = ../../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	ADGVariable.java \
	ADGCtrlVariable.java \
	ADGInVar.java \
	ADGParameter.java \
	ADGFunction.java \
	ADGPort.java \
	ADGInPort.java \
	ADGOutPort.java \
	ADGEdge.java \
	ADGNode.java \
	ADGraph.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

