#
# $Id: makefile,v 1.1 2007/12/07 22:07:44 stefanov Exp $
#

ROOT  = ../..

SUBPACKAGES = \
	codegeneration \
	scheduler \
	platformgeneration \
	platformparameterset \
	consistencychecks \
	transformations

# Java files in this directory
JSRCS = \
	ADGraphToPN.java \
	CDPNToParseTrees.java \
	SynthesizePlatform.java \
	SynthesizeCDPN.java \
	ConsistencyCheck.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

