#
# $Id: makefile,v 1.4 2009/10/21 10:30:35 nikolov Exp $
#

ROOT  = ../..

SUBPACKAGES = \
	dot \
	xml \
	xps \
	ise \
	ipxact \
	hdpc \
	yapiPN \
	ymlPN \
	expression

# Java files in this directory
JSRCS = \
	Visitor.java \
	PlatformVisitor.java \
	GraphVisitor.java \
	ADGraphVisitor.java \
	PNVisitor.java \
	CDPNVisitor.java \
	StatementVisitor.java \
	MappingVisitor.java \
	ExpressionVisitor.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

