#
# $Id: makefile,v 1.2 2009/09/24 12:46:19 sven Exp $
#

ROOT  = ../..

SUBPACKAGES = \
	dot \
	xml \
	xps \
	ise \
	yapiPN \
	ymlPN \
	expression

# Java files in this directory
JSRCS = \
	Visitor.java \
	PlatformVisitor.java \
	GraphVisitor.java \
	ADGraphVisitor.java \
	PNVisitor.java \
	CDPNVisitor.java \
	StatementVisitor.java \
	MappingVisitor.java \
	ExpressionVisitor.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

