#
# $Id: makefile,v 1.1 2008/05/23 15:04:18 stefanov Exp $
#

ROOT  = ../../../..

SUBPACKAGES =

# Java files in this directory
JSRCS = \
	Parser.java \
	ASCII_CharStream.java \
	ASTsign.java \
	ASTIdentifier.java \
	ASTsimpleExpression.java \
	ASTInteger.java \
	ASTspecialOperator.java \
	ASTNLP.java \
	ASTterm.java \
	ASTspecialTerm.java \
	ASTassignStatement.java \
	ASTipdStatement.java \
	ASTopdStatement.java \
	ASTtermOrOperator.java \
	ASTcomplexExpression.java \
	ASTvariable.java \
	ASTcondition.java \
	ASTelseStatement.java \
	ASTforStatement.java \
	ASTfraction.java \
	ASTfunctionDefinitionStatement.java \
	ASTtypeDefinitionStatement.java \
	ASTifStatement.java \
	ASTlistOfIndexStatements.java \
	ASTindexStatement.java \
	ASTindexStatements.java \
	ASTleftVariableList.java \
	ASTrightVariableList.java \
	ASTlinearOperator.java \
	ASTparameterStatement.java \
	ASTmatlabStatement.java \
	JJTParserState.java \
	Node.java \
	ParseException.java \
	Parser.java \
	ParserConstants.java \
	ParserTokenManager.java \
	ParserTreeConstants.java \
	SimpleNode.java \
	Token.java \
	TokenMgrError.java

package: compile

compile:


# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

