#
# $Id: makefile,v 1.1 2007/12/07 22:07:46 stefanov Exp $
#

ROOT  = ../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	CheckPlatform.java \
	CheckMapping.java \
	CrossCheck.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

