#
# $Id: makefile,v 1.2 2010/12/01 09:47:36 svhaastr Exp $
#

ROOT  = ../../../..

SUBPACKAGES = 

# Java files in this directory
JSRCS = \
	ScTimedNetworkVisitor.java \
	ScTimedProcessVisitor.java \
	ScTimedMBStatementVisitor.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

