#
# $Id: makefile,v 1.4 2011/04/20 08:09:02 svhaastr Exp $
#

ROOT  = ../../../..

SUBPACKAGES = 

# Java files in this directory
JSRCS = \
	RuntimeConfig.java \
	ScTimedNetworkVisitor.java \
	ScTimedProcessVisitor.java \
	ScTimedMBStatementVisitor.java \
	ScTimedHWNStatementVisitor.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

