#
# $Id: makefile,v 1.3 2011/03/23 17:58:22 tzhai Exp $
#

ROOT  = ../../../..

SUBPACKAGES = 

# Java files in this directory
JSRCS = \
	RuntimeConfig.java \
	ScTimedNetworkVisitor.java \
	ScTimedProcessVisitor.java \
	ScTimedMBStatementVisitor.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

