#
#
#

ROOT  = ../../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
    CPPDNNVisitorTensorrt.java \
    CPPDNNVisitorARMCL.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

