#
# $Id: makefile,v 1.1 2007/12/07 22:06:44 stefanov Exp $
#

ROOT  = ../..

SUBPACKAGES = \
    ADMXRC2  \
	python


# Java files in this directory
JSRCS = 

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

