#
# $Id: makefile,v 1.1 2007/12/07 22:09:13 stefanov Exp $
#

ROOT  = ../../../..

AUXCLASSPATH = ${VHDL}

# Java packages in this directory
SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	Statement.java  \
	RootStatement.java  \
	AssignStatement.java  \
	OpdStatement.java  \
	IfStatement.java \
	ElseStatement.java \
	ForStatement.java \
	ControlStatement.java \
	MemoryStatement.java \
	FifoMemoryStatement.java \
	VariableStatement.java \
	LhsStatement.java \
	RhsStatement.java \
	NilStatement.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

