#
# $Id: makefile,v 1.1 2010/11/05 16:23:58 svhaastr Exp $
#

ROOT  = ../../../..

SUBPACKAGES = 

# Java files in this directory
JSRCS = \
	ScUntimedNetworkVisitor.java \
	ScUntimedProcessVisitor.java \
	ScUntimedStatementVisitor.java 

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

