#
# $Id: makefile,v 1.2 2011/10/05 15:03:46 nikolov Exp $
#

ROOT  = ../../../../..

GSON = $(ROOT)/../lib/gson.jar
AUXCLASSPATH = $(GSON)

SUBPACKAGES = \
    control \
    supergraph


# Java files in this directory
JSRCS = \
    SBRSConnection.java \
    SBRSLayer.java \
    Supergraph.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

