#
# $Id: makefile,v 1.1 2007/12/07 22:09:06 stefanov Exp $
#

ROOT  = ../../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	Processor.java \
	PowerPC.java \
	MicroBlaze.java \
	ARM.java \
	MemoryMap.java \
	Page.java \
	GPU.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

