#
# $Id: makefile,v 1.1 2008/05/23 08:28:28 stefanov Exp $
#

ROOT  = ../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \


# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

