#
# $Id: makefile,v 1.1 2007/12/07 22:07:48 stefanov Exp $
#

ROOT  = ../../../..

# Java files in this directory
JSRCS = \
	CNNTransformer.java \
	DNNPartition.java \
	DNNPartitioner.java \
	DNNBlockGrouper.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

