#
# $Id: makefile,v 1.1 2007/12/07 22:09:23 stefanov Exp $
#

ROOT  = ..

SUBPACKAGES = \
	polylibBIT 

# Java files in this directory
JSRCS =

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk
