#
# $Id: makefile,v 1.1 2007/12/07 22:09:04 stefanov Exp $
#

ROOT  = ../../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	Controller.java \
	MemoryController.java \
	FifosController.java \
	MultiFifoController.java \
	ReadCrossbarController.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

