#
# $Id: makefile,v 1.1 2007/12/07 22:09:11 stefanov Exp $
#

ROOT  = ../../..

# Java packages in this directory
SUBPACKAGES = \
	statement

# Java files in this directory
JSRCS = \
	ParserNode.java \
	ParserNodeImp.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

