#
# $Id: makefile,v 1.3 2012/02/27 11:22:50 nikolov Exp $
#

ROOT  = ../../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	ADMXRCII.java \
	ADMXPL.java \
	XUPV5LX110T.java \
	ML505.java \
	ML605.java \
	ZedBoard.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

