#
# $Id: makefile,v 1.2 2011/10/20 12:08:44 mohamed Exp $
#

ROOT  = ../../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	ADMXRCII.java \
	ADMXPL.java \
	XUPV5LX110T.java \
	ML505.java \
	ML605.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

