#
# $Id: makefile,v 1.1 2010/04/02 12:21:24 nikolov Exp $
#

ROOT  = ../../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	ADMXRCII.java \
	ADMXPL.java \
	XUPV5LX110T.java \
	ML505.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

