ROOT  = ../../..

# Subdirectories
SUBPACKAGES =

# Java files in this directory
JSRCS = \
	Implementation.java \
	ImplementationTable.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk
