

ROOT  = ../../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	JMatrix.java \
	SignedMatrix.java 

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

