#
# $Id: makefile,v 1.1 2008/05/23 15:04:13 stefanov Exp $
#

ROOT  = ../../..

SUBPACKAGES = \
	scheduler

# Java files in this directory
JSRCS = \


# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

