#
# $Id: makefile,v 1.1 2007/12/07 22:07:04 stefanov Exp $
#

ROOT  = ../../..

SUBPACKAGES = \
	platform \
	pn \
	mapping \
	adg \
	sadg

# Java files in this directory
JSRCS = \


# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

