#
# $Id: makefile,v 1.2 2012/04/02 16:25:40 nikolov Exp $
#

ROOT  = ../../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	ElaborateMany2OneCrossbar.java \
	ElaborateMany2OneCrossbarAXI.java \
	ElaborateMany2One.java \
	ElaborateOne2One.java \
	RefineMemories.java \
	RefineCommunicationMB.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

