#
# $Id: makefile,v 1.1 2007/12/07 22:07:53 stefanov Exp $
#

ROOT  = ../../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	ElaborateMany2OneCrossbar.java \
	ElaborateMany2One.java \
	ElaborateOne2One.java \
	RefineMemories.java \
	RefineCommunicationMB.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

