#
# $Id: makefile,v 1.2 2012/04/02 16:25:40 nikolov Exp $
#

ROOT  = ../../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	Memory.java \
	CM_AXI.java \
	BRAM.java \
	Fifo.java \
	MultiFifo.java \
	ZBT.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

