#
# $Id: makefile,v 1.3 2012/02/23 16:12:37 svhaastr Exp $
#

ROOT  = ../../..

SUBPACKAGES = 

# Java files in this directory
JSRCS = \
	CompaanHWNodeIseVisitor.java \
	ReorderMemoryVisitor.java \
	IseNetworkVisitor.java \
	IseConfig.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

