#
# $Id: makefile,v 1.2 2011/05/17 15:05:35 svhaastr Exp $
#

ROOT  = ../../..

SUBPACKAGES = 

# Java files in this directory
JSRCS = \
	CompaanHWNodeIseVisitor.java \
	ReorderMemoryVisitor.java \
	IseNetworkVisitor.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

