#
# $Id: makefile,v 1.1 2009/09/24 12:46:19 sven Exp $
#

ROOT  = ../../..

SUBPACKAGES = 

# Java files in this directory
JSRCS = \
	CompaanHWNodeIseVisitor.java \
	IseNetworkVisitor.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

