#
# $Id: makefile,v 1.1 2009/10/21 10:30:35 nikolov Exp $
#

ROOT  = ../../..

SUBPACKAGES = 

# Java files in this directory
JSRCS = \
	HdpcNetworkVisitor.java \
	HdpcProcessVisitor.java \
	HdpcStatementVisitor.java 

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

