#
# $Id: makefile,v 1.1 2007/12/07 22:07:47 stefanov Exp $
#

ROOT  = ../../..

SUBPACKAGES = \
	memoryparameters

# Java files in this directory
JSRCS = \
	SetPlatformParameters.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

