

ROOT  = ../../..

SUBPACKAGES = \
	expression \
	matrix 

# Java files in this directory
JSRCS = \

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

