#
# $Id: makefile,v 1.1 2007/12/07 22:09:09 stefanov Exp $
#

ROOT  = ../../..

SUBPACKAGES = \
	adg

# Java files in this directory
JSRCS = \
	NPort.java \
	Edge.java \
	Node.java \
	Graph.java


# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

