#
# $Id: makefile,v 1.2 2011/10/05 15:03:46 nikolov Exp $
#

ROOT  = ../../..

SUBPACKAGES = \
    sesame

# Java files in this directory
JSRCS = \
	CodeGenerationException.java \
	Polytope2IfStatements.java \
	InputPort2MemoryStatement.java \
	OutputPort2OpdStatement.java \
	Function2AssignStatement.java \
	Polytope2ForStatements.java \
	Node2ForStatements.java \
	Node2IfStatements.java \
	Node2ControlStatements.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

