#
# $Id: makefile,v 1.1 2007/12/07 22:07:44 stefanov Exp $
#

ROOT  = ../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	CodeGenerationException.java \
	Polytope2IfStatements.java \
	InputPort2MemoryStatement.java \
	OutputPort2OpdStatement.java \
	Node2AssignStatement.java \
	Polytope2ForStatements.java \
	Node2ForStatements.java \
	Node2IfStatements.java \
	Node2ControlStatements.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

