#
# $Id: makefile,v 1.1 2007/12/07 22:07:28 stefanov Exp $
#

ROOT  = ../../../..

SUBPACKAGES = 

# Java files in this directory
JSRCS = \
	MhsVisitor.java \
	MssVisitor.java \
	FifoCtrlVisitor.java \
	CrossbarVisitor.java \
	CompaanHWNodeVisitor.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

