#
# $Id: makefile,v 1.1 2009/09/25 15:23:34 sven Exp $
#

ROOT  = ../../..

SUBPACKAGES = \
	platform

# Java files in this directory
JSRCS = \
  IpxactXmlWriter.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

