#
# $Id: makefile,v 1.1 2007/12/07 22:09:07 stefanov Exp $
#

ROOT  = ../../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	PLBPort.java \
	OPBPort.java \
	IPLBPort.java \
	DPLBPort.java \
	LMBPort.java \
	ILMBPort.java \
	DLMBPort.java \
	FifoReadPort.java \
	FifoWritePort.java \
	CompaanInPort.java \
	CompaanOutPort.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

