#
# $Id: makefile,v 1.2 2012/04/02 16:25:40 nikolov Exp $
#

ROOT  = ../../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	AXIPort.java \
	PLBPort.java \
	OPBPort.java \
	IPLBPort.java \
	DPLBPort.java \
	LMBPort.java \
	ILMBPort.java \
	DLMBPort.java \
	FifoReadPort.java \
	FifoWritePort.java \
	CompaanInPort.java \
	CompaanOutPort.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

