#
# $Id: makefile,v 1.2 2008/05/23 08:28:28 stefanov Exp $
#

ROOT  = ../../../

GSON = $(ROOT)/../lib/gson.jar
AUXCLASSPATH = $(GSON)

# Java packages in this directory
SUBPACKAGES = \
	cnn \
	csdf \
	pyplot \
	refinement \
	evaluation

# Java files in this directory
JSRCS = \
	JSONParser.java \
	ReferenceResolvable.java


# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk


