#
# $Id: makefile,v 1.1 2007/12/07 22:09:04 stefanov Exp $
#

ROOT  = ../../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	CompaanHWNode.java \
	ReadUnit.java \
	ExecuteUnit.java \
	WriteUnit.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

