#
# $Id: makefile,v 1.2 2010/04/02 12:21:24 nikolov Exp $
#

ROOT  = ../../..

SUBPACKAGES = \
	processors \
	memories \
	ports \
	communication \
	hwnodecompaan \
	controllers \
	peripherals \
	host_interfaces

# Java files in this directory
JSRCS = \
	Port.java \
	Link.java \
	Resource.java \
	Platform.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

