#
# $Id: makefile,v 1.1 2007/12/07 22:09:03 stefanov Exp $
#

ROOT  = ../../..

SUBPACKAGES = \
	processors \
	memories \
	ports \
	communication \
	hwnodecompaan \
	controllers \
	peripherals

# Java files in this directory
JSRCS = \
	Port.java \
	Link.java \
	Resource.java \
	Platform.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

