#
# $Id: makefile,v 1.2 2011/06/10 11:48:27 svhaastr Exp $
#

ROOT  = ../../..

SUBPACKAGES =

# Java files in this directory
JSRCS = \
	VhdlExpressionVisitor.java \
	CExpressionVisitor.java \
	ExpressionAnalyzer.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

