#
# $Id: makefile,v 1.2 2012/04/02 16:25:40 nikolov Exp $
#

ROOT  = ../../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	AXICrossbar.java \
	Crossbar.java \
	LMBBus.java \
	PLBBus.java \
	AXIBus.java \
	TransparentBus.java \
	ReadFifoBus.java \
	WriteFifoBus.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

