#
# $Id: makefile,v 1.3 2012/04/20 23:00:41 mohamed Exp $
#

ROOT  = ../../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	AXICrossbar.java \
	Crossbar.java \
	LMBBus.java \
	PLBBus.java \
	TransparentBus.java \
	ReadFifoBus.java \
	WriteFifoBus.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

