#
# $Id: makefile,v 1.1 2007/12/07 22:09:05 stefanov Exp $
#

ROOT  = ../../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	Crossbar.java \
	LMBBus.java \
	PLBBus.java \
	TransparentBus.java \
	ReadFifoBus.java \
	WriteFifoBus.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

