#
# $Id: makefile,v 1.1 2007/12/07 22:09:02 stefanov Exp $
#

ROOT  = ../../..

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	ControlExpression.java \
	IndexVector.java \
	Polytope.java \
	FilterSet.java \
	LBS.java

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

