#
#
#

ROOT  = ..

PROTOBUF = $(ROOT)/../lib/protobuf-java.jar
AUXCLASSPATH = $(PROTOBUF)

SUBPACKAGES = \

# Java files in this directory
JSRCS = \
	ONNX.java \
	onnxTest.java

	
# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk
