#
#
#

ROOT  = .

PROTOBUF = $(ROOT)/../lib/protobuf-java.jar
AUXCLASSPATH = $(PROTOBUF)

SUBPACKAGES = \
	onnx

# Java files in this directory
JSRCS = \

	
# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk
