#
# $Id: makefile,v 1.1 2007/12/07 22:06:54 stefanov Exp $
#

ROOT  = ../..

# Java packages in this directory
SUBPACKAGES = \
	xml \
	matlab \
	expression \
	matrix

# Java files in this directory
JSRCS = \


# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk


