#
# $Id: makefile,v 1.2 2008/05/23 08:28:28 stefanov Exp $
#

ROOT  = ../..

# Java packages in this directory
SUBPACKAGES = \
	xml \
	matlab \
	expression \
	matrix \
	yapi \
	json \
	onnx

# Java files in this directory
JSRCS = \


# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk


